server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /predict {
        proxy_pass http://glaucoma_project:8000;
        proxy_read_timeout 120s;
        client_max_body_size 20M;
    }

    location /health {
        proxy_pass http://glaucoma_project:8000;
    }

    location /reports {
        proxy_pass http://glaucoma_project:8000;
    }

    location /docs {
        proxy_pass http://glaucoma_project:8000;
    }
}
